services:

  mysqldb:
    image: mysql:8.0
    container_name: mysql-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - pharmacy-network

  backend:
    build: ./backend

    container_name: pharmacy-backend

    restart: always

    depends_on:
      - mysqldb

    environment:
      DB_HOST: mysqldb
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

    ports:
      - "7000:7000"

    networks:
      - pharmacy-network

  frontend:
    build: ./frontend

    container_name: pharmacy-frontend

    restart: always

    depends_on:
      - backend

    ports:
      - "8080:80"

    networks:
      - pharmacy-network

volumes:
  mysql-data:

networks:
  pharmacy-network:
